service: backend-pedidos360
useDotenv: true
provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  role: arn:aws:iam::362471493855:role/LabRole 
  environment:
    TABLA_PEDIDOS: pedidos-tabla-dev
    TABLA_CATALOGO: catalogo-tabla-dev
    ESTADOS_PERMITIDOS: "CREADO,ACEPTADO,EN_PREPARACION,DESPACHADO,ENTREGADO,CANCELADO"
    TOPIC_ARN_SNS: arn:aws:sns:${aws:region}:${aws:accountId}:pedido-aceptado
  httpApi:
    cors: true
    authorizers:
      entraIdAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://login.microsoftonline.com/${env:ENTRA_TENANT_ID}/v2.0
        audience:
          - ${env:ENTRA_CLIENT_ID}


functions:
  crearPedido:
    handler: src.pedidos.crear_pedido
    events:
      - httpApi:
          path: /api/orders
          method: post
          authorizer: 
            name: entraIdAuthorizer
  listarPedidos:
    handler: src.pedidos.listar_pedidos
    events:
      - httpApi:
          path: /api/orders
          method: get
          authorizer: 
            name: entraIdAuthorizer
  obtenerPedido:
    handler: src.pedidos.obtener_pedido
    events:
      - httpApi:
          path: /api/orders/{id}
          method: get
          authorizer: 
            name: entraIdAuthorizer
  actualizarEstadoPedido:
    handler: src.pedidos.actualizar_estado
    events:
      - httpApi:
          path: /api/orders/{id}/estado
          method: patch
          authorizer: 
            name: entraIdAuthorizer

  crearProducto:
    handler: src.catalogo.crear_producto
    events:
      - httpApi:
          path: /api/catalog
          method: post
          authorizer: 
            name: entraIdAuthorizer
  listarProductos:
    handler: src.catalogo.listar_productos
    events:
      - httpApi:
          path: /api/catalog
          method: get
  actualizarStockProducto:
    handler: src.catalogo.actualizar_stock
    events:
      - httpApi:
          path: /api/catalog/{id}/stock
          method: patch
          authorizer: 
            name: entraIdAuthorizer
  actualizarProducto:
    handler: src.catalogo.actualizar_producto
    events:
      - httpApi:
          path: /api/catalog/{id}
          method: patch
          authorizer: 
            name: entraIdAuthorizer
  eliminarProducto:
    handler: src.catalogo.eliminar_producto
    events:
      - httpApi:
          path: /api/catalog/{id}
          method: delete
          authorizer: 
            name: entraIdAuthorizer
  
  descontarStockEvento:
    handler: src.catalogo.descontar_stock_evento
    events:
      - sns: pedido-aceptado

resources:
  Resources:
    TablaPedidosDynamo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pedidos-tabla-dev
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST 

    TablaCatalogoDynamo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: catalogo-tabla-dev
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST