service: backend-pedidos360

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  role: arn:aws:iam::362471493855:role/LabRole 
  environment:
    TABLA_PEDIDOS: pedidos-tabla-dev
    TABLA_CATALOGO: catalogo-tabla-dev
    ESTADOS_PERMITIDOS: "CREADO,ACEPTADO,EN_PREPARACION,DESPACHADO,ENTREGADO,CANCELADO"

functions:
  crearPedido:
    handler: src.pedidos.crear_pedido
    events:
      - http:
          path: /api/orders
          method: post
          cors: true

  obtenerPedido:
    handler: src.pedidos.obtener_pedido
    events:
      - http:
          path: /api/orders/{id}
          method: get
          cors: true

  actualizarEstadoPedido:
    handler: src.pedidos.actualizar_estado
    events:
      - http:
          path: /api/orders/{id}/estado
          method: patch
          cors: true
  crearProducto:
    handler: src.catalogo.crear_producto
    events:
      - http:
          path: /api/catalog
          method: post
          cors: true

  listarProductos:
    handler: src.catalogo.listar_productos
    events:
      - http:
          path: /api/catalog
          method: get
          cors: true

  actualizarStockProducto:
    handler: src.catalogo.actualizar_stock
    events:
      - http:
          path: /api/catalog/{id}/stock
          method: patch
          cors: true

resources:
  Resources:
    TablaPedidosDynamo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pedidos-tabla-dev
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST #

    TablaCatalogoDynamo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: catalogo-tabla-dev
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST